### ISSUE TITLE
Why there is new() method?

### ISSUE THREAD

**Issue by bessarabov** [babf/Text-CSV-Slurp#3]
I like this module but there is one thing I don't understand. In the docs ( https://metacpan.org/pod/Text::CSV::Slurp ) there is information about new() method. But it is not used in any example.

Maybe you should remove it from documentation to make docs a bit simpler?

**Comment by babf** [comment]
Some people prefer the OO style interface and will be using it. e.g.

```
my $slurp = Text::CSV::Slurp->new;
my $data = $slurp->load( file => "foo.csv" );
```

Removing the method (and documentation) will break innumerable installations should they upgrade, and the docs are already pretty simple, so I'm not convinced this would be an improvement.

**Comment by bessarabov** [comment]
Thank you for the explanation. Now it is clear to me how `new()` can be used.

I'm not proposing to remote this method from the code. I'm proposing to remove it only from the documentation.

**Comment by ghost** [comment]
I disagree with removing it from the documentation. It's a public method and should be documented because of that.
