### ISSUE TITLE
CSV file is not correctly parsed from string

### ISSUE THREAD

**Issue by tomas-zemres** [babf/Text-CSV-Slurp#5]
I am not able parse file using:
  Text::CSV::Slurp->load(string => $csv_data);

I must use workaround (it parses $csv_data correctly):
  Text::CSV::Slurp->load(filehandle => IO::Scalar->new(\$csv_data));

There is probably bug on line 41:
 https://github.com/babf/Text-CSV-Slurp/blob/master/lib/Text/CSV/Slurp.pm#L41

 because it does not reflect correct "end of lines" it may be "\n", "\r", "\r\n" (or maybe anything else).

**Comment by babf** [comment]
Please create some tests, make the necessary changes in a fork and give me a pull request. Thanks in advance.

**Comment by ghost** [comment]
Thanks for the patch - have released it in 1.03!
